# -*- coding: utf-8 -*-
{
    'name': 'Dashboards maker',
    'version': '18.0.1.0.0',
    'category': 'Extra Tools',
    'summary': """Show your data in visual format.""",
    'description': """Using this users are able to create dashbaord using the data available in database.
    Data Insights Dashboard odoomatrix
""",
    'author': 'OdooMatrix',
    'company': 'OdooMatrix',
    'maintainer': 'OdooMatrix',
    'website': 'odoomatrix.com',
    'depends': ['base'],
    'data': [
            'security/dashboards_security.xml',
            'security/ir.model.access.csv',
            'data/number_system_data.xml',
            'data/field_aggregates_data.xml',
            'data/number.system.line.csv',
            'data/color.palette.line.csv',
            'data/color_palette_data.xml',
            'data/date_filters_data.xml',
            'views/ir_menu.xml',
            'views/dashboard_dashboard.xml',
            'views/dashboard_chart.xml',
            'views/number_system.xml',
            'views/color_palette.xml',
            'views/date_filters.xml',
            'wizard/dm_dashboard_copy_views.xml',
             ],
    'assets': {
        'web.assets_backend': [
            'dashboard_maker/static/src/components/dashboard_maker_chart/dashboard_maker_chart.xml',
            'dashboard_maker/static/src/components/dashboard_maker_chart/dashboard_maker_chart.js',
            'dashboard_maker/static/src/components/item_options/item_options.xml',
            'dashboard_maker/static/src/components/item_options/item_options.js',
            'dashboard_maker/static/src/components/card_kpi/card_kpi.xml',
            'dashboard_maker/static/src/components/card_kpi/card_kpi.js',
            'dashboard_maker/static/src/js/dashboard.js',
            'dashboard_maker/static/src/js/number_formatter.js',
            'dashboard_maker/static/src/components/list_item/list_item.js',
            'dashboard_maker/static/src/components/filters/model_filter.js',
            'dashboard_maker/static/src/components/filters/field_filter.js',
            'dashboard_maker/static/src/xml/dashboard.xml',
            'dashboard_maker/static/src/components/list_item/list_item.xml',
            'dashboard_maker/static/src/components/filters/model_filter.xml',
            'dashboard_maker/static/src/components/filters/field_filter.xml',
            'dashboard_maker/static/src/widgets/chart_preview.js',
            'dashboard_maker/static/src/widgets/chart_preview.xml',
        ],
        "dashboard_maker.dashboardmaker_lib" : [
            '/dashboard_maker/static/lib/gridStack/gridstack-all.js',
            '/dashboard_maker/static/lib/gridStack/gridstack.min.css',
            '/dashboard_maker/static/lib/echarts/echarts.min.js',
            'dashboard_maker/static/src/scss/list_styles.scss',
            'dashboard_maker/static/src/scss/card_styles.scss',

        ]
    },
    'installable': True,
    'application': False,
    'auto_install': False,
    'license': "OPL-1",
    'price': 0,
    'currency': "USD",
    'support': "dev.odoomatrix@gmail.com",
    "images": ['static/description/banner.png'],
    'uninstall_hook': 'uninstall_hook',
}
